name: worldline_flutter
description: Worldline template Flutter project

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.13.0'

dependencies:
  dio: ^5.3.2
  easy_localization: ^3.0.2
  either_dart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_native_splash: ^2.3.1
  get_it: ^7.6.0
  go_router: ^10.0.0
  injectable: ^2.2.0
  permission_handler: ^10.4.3
  url_launcher: ^6.1.12

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/translations/
    - assets/images/
